### ISSUE TITLE
[ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)] with QGIS Desktop

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/kasm-gis-workspace#1]
ImportError as of https://github.com/capsulecorplab/kasm-gis-workspace/commit/ca57b1160d06dab9014f8c237b5facd35944c970 with QGIS Desktop

![Screenshot from 2022-07-26 10-44-42](https://user-images.githubusercontent.com/14095576/181063554-f86785de-a00b-4c3f-877b-2e2367e0f0da.png)

**Comment by TristanDamron** [comment]
Fixed with 7a8503c0e234c28144823c1346576c11be77f326 

Did some digging online and discovered that the error was due to a known issue with markupsafe. I resolved the issue by force installing an older version (2.0.1) to the container!
